src/Entity/User.php
<?php

namespace App\Entity;

use App\Entity\Pays;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 *  @UniqueEntity("email")
 *  @ORM\HasLifecycleCallbacks()
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     *   @Assert\Email(
     *     message = "l'adresse '{{ value }}' est invalide.",
     *     checkMX = true
     * )
     */
    private $email;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Groupes", inversedBy="users")
     * @ORM\JoinTable(name="users_groups",
     *      joinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="group_id", referencedColumnName="id")}
     * )
     */
    protected $groupes;

    /**
     * @ORM\Column(type="string", length=255)
     *   @Assert\Length(
     *      min = 6,
     *      minMessage = "le mot de passe doit être formé d'au moins {{ limit }} caractères ",
     * )
     */
    private $password;

    /**
     *  @Assert\EqualTo(propertyPath="password", message="les mots de passe ne correspondent pas" )
     *
     */
    public $password_confirm;

    public $password_edit;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Admin", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $admin;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Member", mappedBy="user",  cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $member;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Pays" , cascade={"persist"} )
     */
    private $pays;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Medias", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=true)
     * @Assert\Valid
     */
    private $avatar;

    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="create")
     */
    private $created;

    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="update")
     */
    private $modified;

    public function __construct()
    {
        $this->groupes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->email;
    }

    public function getRoles()
    {
        $role = [];
        foreach ($this->getGroupes() as $value) {
            $role[] = $value->getRole();
        }

        return $role;
    }

    public function getSalt()
    {
    }

    public function eraseCredentials()
    {
    }

    public function getUploadDir()
    {
        return 'uploads';
    }

    protected function getUploadRootDir()
    {
        return __DIR__ . '/../public/' . $this->getUploadDir();
    }

    /**
     * @Groups({"default"})
     */
    public function getImagePath(): ?string
    {
        return '/' . $this->getWebPath();
    }

    public function getWebPath()
    {
        if ($this->getAvatar() != null) {

            $absolutePath = $this->getUploadDir() . '/' . $this->getAvatar()->getId() . '.' . $this->getAvatar()->getUrl();

            if (file_exists($absolutePath)) {
                return $absolutePath;
            } else {
                return $this->getUploadDir() . '/avatar.png';
            }

        } else {
            return $this->getUploadDir() . '/avatar.png';
        }

    }
    public function getIdentifiant()
    {
        return $this->encrypt('encrypt', $this->id);
    }
    public function encrypt($action, $string)
    {
        $output = false;
        $encrypt_method = "AES-256-CBC";
        $secret_key = 'ffgd;jhfserfy@!$DCGGgssd';
        $secret_iv = 'ffgd;jhfserfy@@!$DCGGgssd';
        $key = hash('sha256', $secret_key);

        $iv = substr(hash('sha256', $secret_iv), 0, 16);
        if ($action == 'encrypt') {
            $output = openssl_encrypt($string, $encrypt_method, $key, 0, $iv);
            $output = base64_encode($output);
        } else if ($action == 'decrypt') {
            $output = openssl_decrypt(base64_decode($string), $encrypt_method, $key, 0, $iv);
        }
        return $output;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getModified(): ?\DateTimeInterface
    {
        return $this->modified;
    }

    public function setModified(\DateTimeInterface $modified): self
    {
        $this->modified = $modified;

        return $this;
    }

    /**
     * @return Collection|Groupes[]
     */
    public function getGroupes(): Collection
    {
        return $this->groupes;
    }

    public function addGroupe(Groupes $groupe): self
    {
        if (!$this->groupes->contains($groupe)) {
            $this->groupes[] = $groupe;
        }

        return $this;
    }

    public function removeGroupe(Groupes $groupe): self
    {
        if ($this->groupes->contains($groupe)) {
            $this->groupes->removeElement($groupe);
        }

        return $this;
    }

    public function getAdmin(): ?Admin
    {
        return $this->admin;
    }

    public function setAdmin(?Admin $admin): self
    {
        $this->admin = $admin;

        return $this;
    }

    public function getPays(): ?Pays
    {
        return $this->pays;
    }

    public function setPays(?Pays $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

    public function getAvatar(): ?Medias
    {
        return $this->avatar;
    }

    public function setAvatar(?Medias $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getMember(): ?Member
    {
        return $this->member;
    }

    public function setMember(?Member $member): self
    {
        $this->member = $member;

        return $this;
    }

}

src/Controller/UserAdminController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\PasswordEditType;
use App\Form\UserType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

/**
 * @Route("/admin/user")
 */
class UserAdminController extends AbstractController
{
    /**
     * @Route("/", name="user_admin")
     */
    public function index()
    {
        $em = $this->getDoctrine()->getManager();
        $entities = $em->getRepository(User::class)->findAdmin();

        return $this->render('user_admin/index.html.twig', [
            'entities' => $entities,
        ]);
    }

    /**
     * @Route("/login", name="user_admin_login")
     */
    public function login(AuthenticationUtils $authenticationUtils)
    {
        $error = $authenticationUtils->getLastAuthenticationError();

        $lastUsername = $authenticationUtils->getLastUsername();
        return $this->render('user_admin/login.html.twig', [
            'last_username' => $lastUsername,
            'error' => $error,
        ]);
    }

    /**
     * @Route("/remove/{id}", name="user_admin_remove")
     */
    public function remove(Request $request, User $entity)
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($entity);
        $em->flush();
        $request->getSession()->getFlashBag()->add('ajout', 'L\'élément a bien été supprimé!');
        return $this->redirect($this->generateUrl('user_admin'));

    }

    /**
     * @Route("/show/{id}", name="user_admin_show")
     */
    public function show(User $entity)
    {
        $em = $this->getDoctrine()->getManager();
        return $this->render('user_admin/show.html.twig', [
            'entity' => $entity,
        ]);
    }

    /**
     * @Route("/change-password", name="user_admin_password_change")
     */
    public function passwordCurrentUser(Request $request, UserPasswordEncoderInterface $encoder)
    {
        $entity = $this->getUser();
        $em = $this->getDoctrine()->getManager();
        $form = $this->createForm(PasswordEditType::class, $entity);

        if ($form->handleRequest($request)->isSubmitted() && $form->isValid()) {

            $bool = ($encoder->isPasswordValid($this->getUser(), $request->get('password_edit')['current_password'])) ? true : false;
            if ($bool) {
                $hash = $encoder->encodePassword($entity, $request->get('password_edit')['password_edit']['first']);
                $entity->setPassword($hash);
                $em->flush();
                $request->getSession()->getFlashBag()->add('ajout', 'Opération réussie avec succès !');
            } else {

                $request->getSession()->getFlashBag()->add('error', 'Votre  mot de passe de actuel est incorect !');
            }

        }

        return $this->render('user_admin/passwordEdit.html.twig', [
            'entity' => $entity,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/password-edit/{id}", name="user_admin_password")
     */
    public function password(Request $request, User $entity, UserPasswordEncoderInterface $encoder)
    {
        $em = $this->getDoctrine()->getManager();
        $form = $this->createForm(PasswordEditType::class, $entity);
        $currentUser = false;
        $currentPassword = null;

        if ($form->handleRequest($request)->isSubmitted() && $form->isValid()) {

            $bool = ($encoder->isPasswordValid($this->getUser(), $request->get('password_edit')['current_password'])) ? true : false;
            if ($bool) {
                $hash = $encoder->encodePassword($entity, $request->get('password_edit')['password_edit']['first']);
                $entity->setPassword($hash);
                $em->flush();
                $request->getSession()->getFlashBag()->add('ajout', 'Opération réussie avec succès !');
            } else {

                $request->getSession()->getFlashBag()->add('error', 'Le mot de passe de l\'utilisateur est incorect !');
            }

        }

        return $this->render('user_admin/password.html.twig', [
            'entity' => $entity,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/create/{id}", name="user_admin_create")
     */
    public function create(Request $request, UserPasswordEncoderInterface $encoder, $id = null)
    {
        $em = $this->getDoctrine()->getManager();
        $user = new User();
        $etat = false;
        if ($id != null) {
            $user = $em->getRepository(User::class)->find($id);
        }
        if ($user->getId() != null) {
            $etat = true;
        }

        $form = $this->createForm(UserType::class, $user, ['admin' => true, 'edit' => $etat]);
        if ($form->handleRequest($request)->isSubmitted() && $form->isValid()) {
            //dump($user->getAvatar()->getFile()); die();
            $hash = $encoder->encodePassword($user, $user->getPassword());
            $user->setPassword($hash);
            $em->persist($user);
            $em->flush();
            $request->getSession()->getFlashBag()->add('ajout', 'Opération réussie avec succès !');
            return $this->redirect($this->generateUrl('user_admin_show', array('id' => $user->getId())));

        }

        return $this->render('user_admin/new.html.twig', [
            'form' => $form->createView(),
            'user' => $user,
        ]);
    }

}

templates/user_admin/editUser.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Modifier votre profil {{ parent() }} {% endblock %}

{% block body %}
 <div class="row">
                  

                    <div class="col-12">
                        <div class="block  table-block mb-4">
                            <div class="block-heading">
                                <h5>Modifier votre profil </h5>
                               
                                
                            </div>

                            <div class="row">
                            <div class="col-12" >
                           
                             {{ form_start(form) }}
                               {% for message in app.session.flashbag.get('ajout') %}
                                     
                                <div class="alert alert-success" role="alert">
                                    {{ message }}
                                </div>

                                {% endfor %}
                               
                             <div class="form-row">

                            
                              <div class="form-group col-md-4">
                                
                                {{ form_label(form.admin.nom, 'Nom de l\'administrateur', {'label_attr': {'class': ''}}) }}
                                {{ form_widget(form.admin.nom, {'attr': {'class': 'form-control' , 'placeholder' : 'Nom de l\'administrateur' } }) }}
                                {{ form_errors(form.admin.nom) }}
                            </div>
                             <div class="form-group col-md-4">
                                
                                {{ form_label(form.admin.prenom, 'Prénom de l\'administrateur', {'label_attr': {'class': ''}}) }}
                                {{ form_widget(form.admin.prenom, {'attr': {'class': 'form-control' , 'placeholder' : 'Prénom de l\'administrateur' } }) }}
                                {{ form_errors(form.admin.prenom) }}
                            </div>
                             <div class="form-group col-md-4">
                                
                                {{ form_label(form.admin.fonction, 'Fonction de l\'administrateur', {'label_attr': {'class': ''}}) }}
                                {{ form_widget(form.admin.fonction, {'attr': {'class': 'form-control' , 'placeholder' : 'Fonction de l\'administrateur' } }) }}
                                {{ form_errors(form.admin.fonction) }}
                            </div>
                             <div class="form-group col-md-4">
                                
                                {{ form_label(form.admin.tel, 'Téléphone de l\'administrateur', {'label_attr': {'class': ''}}) }}
                                {{ form_widget(form.admin.tel, {'attr': {'class': 'form-control' , 'placeholder' : 'Téléphone de l\'administrateur' } }) }}
                                {{ form_errors(form.admin.tel) }}
                            </div>

                                 <div class="form-group col-md-4">
                                
                                {{ form_label(form.email, 'Adresse E-mail', {'label_attr': {'class': ''}}) }}
                                {{ form_widget(form.email, {'attr': {'class': 'form-control' , 'placeholder' : 'Adresse E-mail' } }) }}
                                {{ form_errors(form.email) }}
                               </div>
                              
                                <div class="form-group col-md-4">
                                
                                {{ form_label(form.avatar.file, 'Avatar de l\'administrateur', {'label_attr': {'class': ''}}) }}
                                {{ form_widget(form.avatar.file, {'attr': {'class': 'form-control' , 'placeholder' : 'Avatar de l\'administrateur' } }) }}
                                {{ form_errors(form.avatar.file) }}
                               </div>
                            </div>
                              
                                <hr>
                              

                                   <div class="btn-group record_actions">
                                   
                                     <a class="btn btn-inline btn-info" href="{{ path('user_admin_profil') }}">
                                            <i class="fa fa-chevron-circle-left"></i> Retour
                                        </a>

                                        <button class="btn btn-primary" type="submit">Valider</button>
                                    </div>
                             {{ form_end(form) }}

                             </div>

                            </div>

                        </div>
                    </div>

                </div>
{% endblock %}

templates/user_admin/index.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Liste Utilisateur {{ parent() }} {% endblock %}

{% block body %}
<div class="row">


    <div class="col-12">
        <div class="block  table-block mb-4">
            <div class="block-heading">
                <h5>Liste des utilisateurs </h5>


            </div>


            <div class="row">
                <div class="pull-right">
                    <a href="{{ path('user_admin_create') }}" class="btn btn-primary">Ajouter</a>
                    <br><br>
                </div>


                <div class="table-responsive">
                    {% for message in app.session.flashbag.get('ajout') %}

                    <div class="alert alert-success" role="alert">
                        {{ message }}
                    </div>

                    {% endfor %}
                    <table id="dataTable1" class="table-bordered display table table-striped" data-table="data-table">
                        <thead>
                            <tr>
                                <th>Nom</th>
                                <th>Prénom</th>
                                <th>Fonction</th>
                                <th>E-mail</th>
                                <th>Téléphone</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for entity  in entities %}
                            <tr>
                                <td class="name">{{entity.admin.nom}}</td>
                                <td>{{entity.admin.prenom}}</td>
                                <td>{{entity.admin.fonction}}</td>
                                <td>{{entity.email}}</td>
                                <td>{{entity.admin.tel}}</td>
                                <td>
                                    <a class="btn btn-default btn-sm"
                                        href="{{ path('user_admin_show' , {id:entity.id} ) }}">
                                        <i class="fa fa-eye"></i>
                                    </a>

                                </td>
                            </tr>
                            {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>

</div>
{% endblock %}

templates/user_admin/login.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta content="ie=edge" http-equiv="x-ua-compatible">
   
    <title>Connexion Administrateur | Administration Asfrik!</title>
    

    <!--favicon-->
    <link href="assets/images/favicon.ico" rel="shortcut icon">

    <!--Preloader-CSS-->
    <link rel="stylesheet" href="{{ asset('admin/assets/plugins/preloader/preloader.css') }}">

    <!--bootstrap-4-->
    <link rel="stylesheet" href="{{ asset('admin/assets/css/bootstrap.min.css') }}">

    <!--Custom Scroll-->
    <link rel="stylesheet" href="{{ asset('admin/assets/plugins/customScroll/jquery.mCustomScrollbar.min.css') }}">
    <!--Font Icons-->
    <link rel="stylesheet" href="{{ asset('admin/assets/icons/simple-line/css/simple-line-icons.css') }}">
    <link rel="stylesheet" href="{{ asset('admin/assets/icons/dripicons/dripicons.css') }}">
    <link rel="stylesheet" href="{{ asset('admin/assets/icons/ionicons/css/ionicons.min.css') }}">
    <link rel="stylesheet" href="{{ asset('admin/assets/icons/eightyshades/eightyshades.css') }}">
    <link rel="stylesheet" href="{{ asset('admin/assets/icons/fontawesome/css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ asset('admin/assets/icons/foundation/foundation-icons.css') }}">
    <link rel="stylesheet" href="{{ asset('admin/assets/icons/metrize/metrize.css') }}">
    <link rel="stylesheet" href="{{ asset('admin/assets/icons/typicons/typicons.min.css') }}">
    <link rel="stylesheet" href="{{ asset('admin/assets/icons/weathericons/css/weather-icons.min.css') }}">

    <!--Date-range-->
    <link rel="stylesheet" href="{{ asset('admin/assets/plugins/date-range/daterangepicker.css') }}">
    <!--Drop-Zone-->
    <link rel="stylesheet" href="{{ asset('admin/assets/plugins/dropzone/dropzone.css') }}">
    <!--Full Calendar-->
    <link rel="stylesheet" href="{{ asset('admin/assets/plugins/full-calendar/fullcalendar.min.css') }}">
    <!--Normalize Css-->
    <link rel="stylesheet" href="{{ asset('admin/assets/css/normalize.css') }}">
    <!--Main Css-->
    <link rel="stylesheet" href="{{ asset('admin/assets/css/main.css') }}"> 
</head>
<body>



<section style="background: url({{asset('admin/img/pexels-photo-176851.jpeg')}});background-size: cover">
    <div class="height-100-vh bg-primary-trans">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-12 col-md-6 col-lg-4">
                    <div class="login-div">
                        <p class="logo mb-1">Connexion Administrateur</p>
                        <form id="needs-validation" action="{{path('user_admin_login')}}" method="post" >
                        
                            
                        
                    {% if error %}
                        <div class="alert alert-danger" role="alert">
                        <div>{{ error.messageKey|trans(error.messageData, 'security') }}</div>
                                </div>
                    {% endif %}

                        <input type="hidden" name="_csrf_token"
                                            value="{{ csrf_token('authenticate') }}"
                                        >

                            <div class="form-group">
                                <label>E-mail</label>
                                <input class="form-control input-lg" name="_username" value="{{ last_username }}" placeholder="E-mail" type="text" required>
                            </div>
                            <div class="form-group">
                                <label>Mot de passe</label>
                                <input class="form-control input-lg" name="_password" placeholder="Mot de passe" type="password" required>
                            </div>

                          
                            <button class="btn btn-primary mt-2">Connexion</button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!--Jquery-->
<script type="text/javascript" src="{{ asset('admin/assets/js/jquery-3.2.1.min.js') }}"></script>
<!--Bootstrap Js-->
<script type="text/javascript" src="{{ asset('admin/assets/js/popper.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('admin/assets/js/bootstrap.min.js') }}"></script>
<!--Modernizr Js-->
<script type="text/javascript" src="{{ asset('admin/assets/js/modernizr.custom.js') }}"></script>

<!--Morphin Search JS-->
<script type="text/javascript" src="{{ asset('admin/assets/plugins/morphin-search/classie.js') }}"></script>
<script type="text/javascript" src="{{ asset('admin/assets/plugins/morphin-search/morphin-search.js') }}"></script>
<!--Morphin Search JS-->
<script type="text/javascript" src="{{ asset('admin/assets/plugins/preloader/pathLoader.js') }}"></script>
<script type="text/javascript" src="{{ asset('admin/assets/plugins/preloader/preloader-main.js') }}"></script>

<!--Chart js-->
<script type="text/javascript" src="{{ asset('admin/assets/plugins/charts/Chart.min.js') }}"></script>

<!--Sparkline Chart Js-->
<script type="text/javascript" src="{{ asset('admin/assets/plugins/sparkline/jquery.sparkline.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('admin/assets/plugins/sparkline/jquery.charts-sparkline.js') }}"></script>

<!--Custom Scroll-->
<script type="text/javascript" src="{{ asset('admin/assets/plugins/customScroll/jquery.mCustomScrollbar.min.js') }}"></script>
<!--Sortable Js-->
<script type="text/javascript" src="{{ asset('admin/assets/plugins/sortable2/sortable.min.js') }}"></script>
<!--DropZone Js-->
<script type="text/javascript" src="{{ asset('admin/assets/plugins/dropzone/dropzone.js') }}"></script>
<!--Date Range JS-->
<script type="text/javascript" src="{{ asset('admin/assets/plugins/date-range/moment.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('admin/assets/plugins/date-range/daterangepicker.js') }}"></script>
<!--CK Editor JS-->
<script type="text/javascript" src="{{ asset('admin/assets/plugins/ckEditor/ckeditor.js') }}"></script>
<!--Data-Table JS-->
<script type="text/javascript" src="{{ asset('admin/assets/plugins/data-tables/datatables.min.js') }}"></script>
<!--Editable JS-->
<script type="text/javascript" src="{{ asset('admin/assets/plugins/editable/editable.js') }}"></script>
<!--Full Calendar JS-->
<script type="text/javascript" src="{{ asset('admin/assets/plugins/full-calendar/fullcalendar.min.js') }}"></script>

<!--- Main JS -->
<script src="{{ asset('admin/assets/js/main.js') }}"></script>

</body>

</html>

templates/user_admin/show.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Afficher le profil de l'utilisateur {{ parent() }} {% endblock %}

{% block body %}
<div class="row">


    <div class="col-12">
        <div class="block  table-block mb-4">
            <div class="block-heading">
                <h5>Profil de l'administrateur {{entity.admin.nom}} </h5>


            </div>

            <div class="row">
                <div class="col-12">

                    {% for message in app.session.flashbag.get('ajout') %}

                    <div class="alert alert-success" role="alert">
                        {{ message }}
                    </div>

                    {% endfor %}

                    <table class="table table-hover record_properties">
                        <tbody>
                            <tr>
                                <th scope="row"></th>
                                <td>
                                    <img src="{{asset(entity.WebPath)}}" style="height:120px;"> </td>
                            </tr>
                            <tr>
                                <th scope="row">Nom</th>
                                <td>{{entity.admin.nom}}</td>
                            </tr>

                            <tr>
                                <th scope="row">Prénom</th>
                                <td> {{entity.admin.prenom}} </td>
                            </tr>

                            <tr>
                                <th scope="row">Téléphone</th>
                                <td>{{entity.admin.tel}}</td>
                            </tr>

                            <tr>
                                <th scope="row">Email</th>
                                <td>{{entity.email}}</td>
                            </tr>

                            <tr>
                                <th scope="row">Fonction</th>
                                <td>{{entity.admin.fonction}}</td>
                            </tr>


                        </tbody>
                    </table>

                    <div class="btn-group record_actions">

                        <a class="btn btn-inline btn-info" href="{{path('user_admin')}}">
                            <i class="fa fa-chevron-circle-left"></i> Retour
                        </a>

                        <a class="btn btn-inline btn-primary"
                            href="{{path('user_admin_create' , {id:entity.id} )}}">
                            Modifier <i class="fa fa-edit"></i>
                        </a>
                        <a href="#" class="btn btn-inline btn-danger" data-target="#removeModalLabel"
                            data-toggle="modal">
                            Supprimer <i class="fa fa-trash"></i>
                        </a>

                        <a class="btn btn-inline btn-warning"
                            href="{{path('user_admin_password' , {id:entity.id} )}}">
                            Modifier mot de passe <i class="fa fa-eye-slash"></i>
                        </a>
                    </div>



                </div>

            </div>

        </div>
    </div>

</div>
<div aria-hidden="true" aria-labelledby="removeModalLabel" class="modal fade" id="removeModalLabel" role="dialog"
    tabindex="-1">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Confirmation de suppression</h5>
                <button aria-label="Close" class="close" data-dismiss="modal" type="button"><span aria-hidden="true">
                        ×</span></button>
            </div>
            <div class="modal-body">
                <p style="text-align:center">Voulez-vous vraiment supprimer l'element? </p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary" data-dismiss="modal" type="button"> Annuler</button>
                <a href="{{path('user_admin_remove', {id:entity.identifiant} )}}" class="btn btn-primary">Confirmer </a>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}